// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using Phycocarbon.Infrastructure.Persistence;

#nullable disable

namespace Phycocarbon.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Phycocarbon.Domain.Entities.AlertaCritico", b =>
                {
                    b.Property<Guid>("IdAlerta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("id_alerta");

                    b.Property<DateTime>("DtAlerta")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("dt_alerta");

                    b.Property<Guid>("IdMetrica")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("id_metrica");

                    b.Property<Guid>("IdTanque")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("id_tanque");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("mensagem");

                    b.Property<string>("Severidade")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("severidade");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("status");

                    b.Property<string>("TipoAlerta")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("tipo_alerta");

                    b.HasKey("IdAlerta");

                    b.HasIndex("IdMetrica");

                    b.HasIndex("IdTanque");

                    b.ToTable("TB_ALERTA_CRITICO", (string)null);
                });

            modelBuilder.Entity("Phycocarbon.Domain.Entities.DadoOrbital", b =>
                {
                    b.Property<Guid>("IdDadoOrbital")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("id_dado_orbital");

                    b.Property<DateTime>("DtColeta")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("dt_coleta");

                    b.Property<string>("Fonte")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("fonte");

                    b.Property<Guid>("IdFazenda")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("id_fazenda");

                    b.Property<decimal?>("IrradianciaPar")
                        .HasPrecision(10, 2)
                        .HasColumnType("DECIMAL(10,2)")
                        .HasColumnName("irradiancia_par");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("DECIMAL(10,7)")
                        .HasColumnName("latitude");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("DECIMAL(10,7)")
                        .HasColumnName("longitude");

                    b.Property<decimal?>("Nebulosidade")
                        .HasPrecision(5, 2)
                        .HasColumnType("DECIMAL(5,2)")
                        .HasColumnName("nebulosidade");

                    b.Property<decimal?>("TemperaturaAmbiente")
                        .HasPrecision(4, 2)
                        .HasColumnType("DECIMAL(4,2)")
                        .HasColumnName("temperatura_ambiente");

                    b.HasKey("IdDadoOrbital");

                    b.HasIndex("IdFazenda");

                    b.ToTable("TB_DADO_ORBITAL", (string)null);
                });

            modelBuilder.Entity("Phycocarbon.Domain.Entities.DispositivoIot", b =>
                {
                    b.Property<Guid>("IdDispositivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("id_dispositivo");

                    b.Property<bool>("Ativo")
                        .HasColumnType("BOOLEAN")
                        .HasColumnName("ativo");

                    b.Property<string>("CodigoSerie")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("codigo_serie");

                    b.Property<DateTime>("DtInstalacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("dt_instalacao");

                    b.Property<Guid>("IdTanque")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("id_tanque");

                    b.Property<string>("Modelo")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("modelo");

                    b.Property<string>("TopicoMqtt")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("topico_mqtt");

                    b.HasKey("IdDispositivo");

                    b.HasIndex("IdTanque");

                    b.ToTable("TB_DISPOSITIVO_IOT", (string)null);
                });

            modelBuilder.Entity("Phycocarbon.Domain.Entities.Fazenda", b =>
                {
                    b.Property<Guid>("IdFazenda")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("id_fazenda");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("cidade");

                    b.Property<DateTime>("DtCadastro")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("dt_cadastro");

                    b.Property<Guid>("IdUsuarioResponsavel")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("id_usuario_responsavel");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("DECIMAL(10,7)")
                        .HasColumnName("latitude");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("DECIMAL(10,7)")
                        .HasColumnName("longitude");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("nome");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("status");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("NVARCHAR2(2)")
                        .HasColumnName("uf");

                    b.HasKey("IdFazenda");

                    b.HasIndex("IdUsuarioResponsavel");

                    b.ToTable("TB_FAZENDA", (string)null);
                });

            modelBuilder.Entity("Phycocarbon.Domain.Entities.MetricaTanque", b =>
                {
                    b.Property<Guid>("IdMetrica")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("id_metrica");

                    b.Property<DateTime>("DtLeitura")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("dt_leitura");

                    b.Property<Guid>("IdDispositivo")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("id_dispositivo");

                    b.Property<Guid>("IdTanque")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("id_tanque");

                    b.Property<decimal?>("Luminosidade")
                        .HasPrecision(10, 2)
                        .HasColumnType("DECIMAL(10,2)")
                        .HasColumnName("luminosidade");

                    b.Property<string>("PayloadOriginal")
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("payload_original");

                    b.Property<decimal?>("Ph")
                        .HasPrecision(4, 2)
                        .HasColumnType("DECIMAL(4,2)")
                        .HasColumnName("ph");

                    b.Property<decimal?>("Temperatura")
                        .HasPrecision(4, 2)
                        .HasColumnType("DECIMAL(4,2)")
                        .HasColumnName("temperatura");

                    b.Property<decimal?>("Turbidez")
                        .HasPrecision(4, 2)
                        .HasColumnType("DECIMAL(4,2)")
                        .HasColumnName("turbidez");

                    b.HasKey("IdMetrica");

                    b.HasIndex("IdDispositivo");

                    b.HasIndex("IdTanque");

                    b.ToTable("TB_METRICAS_TANQUE", (string)null);
                });

            modelBuilder.Entity("Phycocarbon.Domain.Entities.Perfil", b =>
                {
                    b.Property<Guid>("IdPerfil")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("id_perfil");

                    b.Property<string>("Descricao")
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("descricao");

                    b.Property<string>("NomePerfil")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("nome_perfil");

                    b.HasKey("IdPerfil");

                    b.HasIndex("NomePerfil")
                        .IsUnique();

                    b.ToTable("TB_PERFIL", (string)null);
                });

            modelBuilder.Entity("Phycocarbon.Domain.Entities.PrevisaoIa", b =>
                {
                    b.Property<Guid>("IdPrevisao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("id_previsao");

                    b.Property<decimal>("BiomassaGL")
                        .HasPrecision(10, 2)
                        .HasColumnType("DECIMAL(10,2)")
                        .HasColumnName("biomassa_gl");

                    b.Property<decimal>("ConfiancaPct")
                        .HasPrecision(5, 2)
                        .HasColumnType("DECIMAL(5,2)")
                        .HasColumnName("confianca_pct");

                    b.Property<DateTime>("DtPicoPrevisto")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("dt_pico_previsto");

                    b.Property<DateTime>("DtPrevisao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("dt_previsao");

                    b.Property<Guid>("IdDadoOrbital")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("id_dado_orbital");

                    b.Property<Guid>("IdTanque")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("id_tanque");

                    b.Property<string>("ModeloUtilizado")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("modelo_utilizado");

                    b.HasKey("IdPrevisao");

                    b.HasIndex("IdDadoOrbital");

                    b.HasIndex("IdTanque");

                    b.ToTable("TB_PREVISOES_IA", (string)null);
                });

            modelBuilder.Entity("Phycocarbon.Domain.Entities.Tanque", b =>
                {
                    b.Property<Guid>("IdTanque")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("id_tanque");

                    b.Property<decimal>("CapacidadeLitros")
                        .HasPrecision(10, 2)
                        .HasColumnType("DECIMAL(10,2)")
                        .HasColumnName("capacidade_litros");

                    b.Property<string>("CodigoTanque")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("codigo_tanque");

                    b.Property<DateTime>("DtInstalacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("dt_instalacao");

                    b.Property<Guid>("IdFazenda")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("id_fazenda");

                    b.Property<decimal>("PhMax")
                        .HasPrecision(4, 2)
                        .HasColumnType("DECIMAL(4,2)")
                        .HasColumnName("ph_max");

                    b.Property<decimal>("PhMin")
                        .HasPrecision(4, 2)
                        .HasColumnType("DECIMAL(4,2)")
                        .HasColumnName("ph_min");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("status");

                    b.Property<decimal>("TemperaturaMax")
                        .HasPrecision(4, 2)
                        .HasColumnType("DECIMAL(4,2)")
                        .HasColumnName("temperatura_max");

                    b.Property<decimal>("TemperaturaMin")
                        .HasPrecision(4, 2)
                        .HasColumnType("DECIMAL(4,2)")
                        .HasColumnName("temperatura_min");

                    b.Property<string>("TipoAlga")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("tipo_alga");

                    b.HasKey("IdTanque");

                    b.HasIndex("IdFazenda");

                    b.ToTable("TB_TANQUE", (string)null);
                });

            modelBuilder.Entity("Phycocarbon.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("id_usuario");

                    b.Property<DateTime>("DtCriacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("dt_criacao");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("email");

                    b.Property<Guid>("IdPerfil")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("id_perfil");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("nome");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("senha_hash");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("status");

                    b.Property<string>("Telefone")
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("telefone");

                    b.HasKey("IdUsuario");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("IdPerfil");

                    b.ToTable("TB_USUARIO", (string)null);
                });

            modelBuilder.Entity("Phycocarbon.Domain.Entities.AlertaCritico", b =>
                {
                    b.HasOne("Phycocarbon.Domain.Entities.MetricaTanque", "Metrica")
                        .WithMany("Alertas")
                        .HasForeignKey("IdMetrica")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Phycocarbon.Domain.Entities.Tanque", "Tanque")
                        .WithMany("Alertas")
                        .HasForeignKey("IdTanque")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Metrica");

                    b.Navigation("Tanque");
                });

            modelBuilder.Entity("Phycocarbon.Domain.Entities.DadoOrbital", b =>
                {
                    b.HasOne("Phycocarbon.Domain.Entities.Fazenda", "Fazenda")
                        .WithMany("DadosOrbitais")
                        .HasForeignKey("IdFazenda")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fazenda");
                });

            modelBuilder.Entity("Phycocarbon.Domain.Entities.DispositivoIot", b =>
                {
                    b.HasOne("Phycocarbon.Domain.Entities.Tanque", "Tanque")
                        .WithMany("Dispositivos")
                        .HasForeignKey("IdTanque")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tanque");
                });

            modelBuilder.Entity("Phycocarbon.Domain.Entities.Fazenda", b =>
                {
                    b.HasOne("Phycocarbon.Domain.Entities.Usuario", "UsuarioResponsavel")
                        .WithMany("Fazendas")
                        .HasForeignKey("IdUsuarioResponsavel")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UsuarioResponsavel");
                });

            modelBuilder.Entity("Phycocarbon.Domain.Entities.MetricaTanque", b =>
                {
                    b.HasOne("Phycocarbon.Domain.Entities.DispositivoIot", "Dispositivo")
                        .WithMany("Metricas")
                        .HasForeignKey("IdDispositivo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Phycocarbon.Domain.Entities.Tanque", "Tanque")
                        .WithMany("Metricas")
                        .HasForeignKey("IdTanque")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dispositivo");

                    b.Navigation("Tanque");
                });

            modelBuilder.Entity("Phycocarbon.Domain.Entities.PrevisaoIa", b =>
                {
                    b.HasOne("Phycocarbon.Domain.Entities.DadoOrbital", "DadoOrbital")
                        .WithMany("Previsoes")
                        .HasForeignKey("IdDadoOrbital")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Phycocarbon.Domain.Entities.Tanque", "Tanque")
                        .WithMany("Previsoes")
                        .HasForeignKey("IdTanque")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DadoOrbital");

                    b.Navigation("Tanque");
                });

            modelBuilder.Entity("Phycocarbon.Domain.Entities.Tanque", b =>
                {
                    b.HasOne("Phycocarbon.Domain.Entities.Fazenda", "Fazenda")
                        .WithMany("Tanques")
                        .HasForeignKey("IdFazenda")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fazenda");
                });

            modelBuilder.Entity("Phycocarbon.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("Phycocarbon.Domain.Entities.Perfil", "Perfil")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdPerfil")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Perfil");
                });

            modelBuilder.Entity("Phycocarbon.Domain.Entities.DadoOrbital", b =>
                {
                    b.Navigation("Previsoes");
                });

            modelBuilder.Entity("Phycocarbon.Domain.Entities.DispositivoIot", b =>
                {
                    b.Navigation("Metricas");
                });

            modelBuilder.Entity("Phycocarbon.Domain.Entities.Fazenda", b =>
                {
                    b.Navigation("DadosOrbitais");

                    b.Navigation("Tanques");
                });

            modelBuilder.Entity("Phycocarbon.Domain.Entities.MetricaTanque", b =>
                {
                    b.Navigation("Alertas");
                });

            modelBuilder.Entity("Phycocarbon.Domain.Entities.Perfil", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Phycocarbon.Domain.Entities.Tanque", b =>
                {
                    b.Navigation("Alertas");

                    b.Navigation("Dispositivos");

                    b.Navigation("Metricas");

                    b.Navigation("Previsoes");
                });

            modelBuilder.Entity("Phycocarbon.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Fazendas");
                });
#pragma warning restore 612, 618
        }
    }
}
