// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using Phycocarbon.Infrastructure.Persistence;

#nullable disable

namespace Phycocarbon.Infrastructure.Migrations
{
    [DbContext(typeof(PhycocarbonContext))]
    partial class PhycocarbonContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DispositivoIot", b =>
                {
                    b.Property<long>("IdDispositivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_DISPOSITIVO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdDispositivo"));

                    b.Property<string>("Ativo")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("NVARCHAR2(1)")
                        .HasColumnName("ATIVO");

                    b.Property<string>("CodigoSerie")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("CODIGO_SERIE");

                    b.Property<DateTime>("DtInstalacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_INSTALACAO");

                    b.Property<long>("IdTanque")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_TANQUE");

                    b.Property<string>("Modelo")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("MODELO");

                    b.Property<string>("TopicoMqtt")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("TOPICO_MQTT");

                    b.HasKey("IdDispositivo");

                    b.HasIndex("IdTanque");

                    b.ToTable("TB_DISPOSITIVO_IOT", (string)null);
                });

            modelBuilder.Entity("Phycocarbon.Domain.Entities.AlertaCritico", b =>
                {
                    b.Property<long>("IdAlerta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_ALERTA");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdAlerta"));

                    b.Property<DateTime>("DtAlerta")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_ALERTA");

                    b.Property<long>("IdMetrica")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_METRICA");

                    b.Property<long>("IdTanque")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_TANQUE");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("MENSAGEM");

                    b.Property<string>("Severidade")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("SEVERIDADE");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("STATUS");

                    b.Property<string>("TipoAlerta")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("TIPO_ALERTA");

                    b.HasKey("IdAlerta");

                    b.HasIndex("IdMetrica");

                    b.HasIndex("IdTanque");

                    b.ToTable("TB_ALERTA_CRITICO", (string)null);
                });

            modelBuilder.Entity("Phycocarbon.Domain.Entities.DadoOrbital", b =>
                {
                    b.Property<long>("IdDadoOrbital")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_DADO_ORBITAL");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdDadoOrbital"));

                    b.Property<DateTime>("DtColeta")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_COLETA");

                    b.Property<string>("Fonte")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("FONTE");

                    b.Property<long>("IdFazenda")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_FAZENDA");

                    b.Property<decimal?>("IrradianciaPar")
                        .HasPrecision(8, 3)
                        .HasColumnType("DECIMAL(8,3)")
                        .HasColumnName("IRRADIANCIA_PAR");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("DECIMAL(10,7)")
                        .HasColumnName("LATITUDE");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(11, 7)
                        .HasColumnType("DECIMAL(11,7)")
                        .HasColumnName("LONGITUDE");

                    b.Property<decimal?>("Nebulosidade")
                        .HasPrecision(5, 2)
                        .HasColumnType("DECIMAL(5,2)")
                        .HasColumnName("NEBULOSIDADE");

                    b.Property<decimal?>("TemperaturaAmbiente")
                        .HasPrecision(6, 2)
                        .HasColumnType("DECIMAL(6,2)")
                        .HasColumnName("TEMPERATURA_AMBIENTE");

                    b.HasKey("IdDadoOrbital");

                    b.HasIndex("IdFazenda");

                    b.ToTable("TB_DADO_ORBITAL", (string)null);
                });

            modelBuilder.Entity("Phycocarbon.Domain.Entities.Fazenda", b =>
                {
                    b.Property<long>("IdFazenda")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_FAZENDA");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdFazenda"));

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("NVARCHAR2(80)")
                        .HasColumnName("CIDADE");

                    b.Property<DateTime>("DtCadastro")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_CADASTRO");

                    b.Property<long>("IdUsuarioResponsavel")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_USUARIO_RESPONSAVEL");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("DECIMAL(10,7)")
                        .HasColumnName("LATITUDE");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(11, 7)
                        .HasColumnType("DECIMAL(11,7)")
                        .HasColumnName("LONGITUDE");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NOME");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("STATUS");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("NVARCHAR2(2)")
                        .HasColumnName("UF");

                    b.HasKey("IdFazenda");

                    b.HasIndex("IdUsuarioResponsavel");

                    b.ToTable("TB_FAZENDA", (string)null);
                });

            modelBuilder.Entity("Phycocarbon.Domain.Entities.MetricaTanque", b =>
                {
                    b.Property<long>("IdMetrica")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_METRICA");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdMetrica"));

                    b.Property<DateTime>("DtLeitura")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_LEITURA");

                    b.Property<long>("IdDispositivo")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_DISPOSITIVO");

                    b.Property<long>("IdTanque")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_TANQUE");

                    b.Property<decimal?>("Luminosidade")
                        .HasPrecision(10, 2)
                        .HasColumnType("DECIMAL(10,2)")
                        .HasColumnName("LUMINOSIDADE");

                    b.Property<string>("PayloadOriginal")
                        .HasMaxLength(4000)
                        .HasColumnType("NCLOB")
                        .HasColumnName("PAYLOAD_ORIGINAL");

                    b.Property<decimal?>("Ph")
                        .HasPrecision(5, 2)
                        .HasColumnType("DECIMAL(5,2)")
                        .HasColumnName("PH");

                    b.Property<decimal?>("Temperatura")
                        .HasPrecision(6, 2)
                        .HasColumnType("DECIMAL(6,2)")
                        .HasColumnName("TEMPERATURA");

                    b.Property<decimal?>("Turbidez")
                        .HasPrecision(8, 3)
                        .HasColumnType("DECIMAL(8,3)")
                        .HasColumnName("TURBIDEZ");

                    b.HasKey("IdMetrica");

                    b.HasIndex("IdDispositivo");

                    b.HasIndex("IdTanque");

                    b.ToTable("TB_METRICAS_TANQUE", (string)null);
                });

            modelBuilder.Entity("Phycocarbon.Domain.Entities.Perfil", b =>
                {
                    b.Property<long>("IdPerfil")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_PERFIL");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdPerfil"));

                    b.Property<string>("Descricao")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("DESCRICAO");

                    b.Property<string>("NomePerfil")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("NOME_PERFIL");

                    b.HasKey("IdPerfil");

                    b.HasIndex("NomePerfil")
                        .IsUnique();

                    b.ToTable("TB_PERFIL", (string)null);
                });

            modelBuilder.Entity("Phycocarbon.Domain.Entities.PrevisaoIa", b =>
                {
                    b.Property<long>("IdPrevisao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_PREVISAO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdPrevisao"));

                    b.Property<decimal>("BiomassaGL")
                        .HasPrecision(8, 4)
                        .HasColumnType("DECIMAL(8,4)")
                        .HasColumnName("BIOMASSA_G_L");

                    b.Property<decimal>("ConfiancaPct")
                        .HasPrecision(5, 2)
                        .HasColumnType("DECIMAL(5,2)")
                        .HasColumnName("CONFIANCA_PCT");

                    b.Property<DateTime>("DtPicoPrevisto")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_PICO_PREVISTO");

                    b.Property<DateTime>("DtPrevisao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_PREVISAO");

                    b.Property<long>("IdDadoOrbital")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_DADO_ORBITAL");

                    b.Property<long>("IdTanque")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_TANQUE");

                    b.Property<string>("ModeloUtilizado")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("MODELO_UTILIZADO");

                    b.HasKey("IdPrevisao");

                    b.HasIndex("IdDadoOrbital");

                    b.HasIndex("IdTanque");

                    b.ToTable("TB_PREVISOES_IA", (string)null);
                });

            modelBuilder.Entity("Phycocarbon.Domain.Entities.Tanque", b =>
                {
                    b.Property<long>("IdTanque")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_TANQUE");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdTanque"));

                    b.Property<decimal>("CapacidadeLitros")
                        .HasPrecision(10, 2)
                        .HasColumnType("DECIMAL(10,2)")
                        .HasColumnName("CAPACIDADE_LITROS");

                    b.Property<string>("CodigoTanque")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("CODIGO_TANQUE");

                    b.Property<DateTime>("DtInstalacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_INSTALACAO");

                    b.Property<long>("IdFazenda")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_FAZENDA");

                    b.Property<decimal>("PhMax")
                        .HasPrecision(4, 2)
                        .HasColumnType("DECIMAL(4,2)")
                        .HasColumnName("PH_MAX");

                    b.Property<decimal>("PhMin")
                        .HasPrecision(4, 2)
                        .HasColumnType("DECIMAL(4,2)")
                        .HasColumnName("PH_MIN");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("NVARCHAR2(15)")
                        .HasColumnName("STATUS");

                    b.Property<decimal>("TemperaturaMax")
                        .HasPrecision(5, 2)
                        .HasColumnType("DECIMAL(5,2)")
                        .HasColumnName("TEMPERATURA_MAX");

                    b.Property<decimal>("TemperaturaMin")
                        .HasPrecision(5, 2)
                        .HasColumnType("DECIMAL(5,2)")
                        .HasColumnName("TEMPERATURA_MIN");

                    b.Property<string>("TipoAlga")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("TIPO_ALGA");

                    b.HasKey("IdTanque");

                    b.HasIndex("IdFazenda");

                    b.ToTable("TB_TANQUE", (string)null);
                });

            modelBuilder.Entity("Phycocarbon.Domain.Entities.Usuario", b =>
                {
                    b.Property<long>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_USUARIO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdUsuario"));

                    b.Property<DateTime>("DtCriacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_CRIACAO");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("EMAIL");

                    b.Property<long>("IdPerfil")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_PERFIL");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NOME");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("SENHA_HASH");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("NVARCHAR2(1)")
                        .HasColumnName("STATUS");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("TELEFONE");

                    b.HasKey("IdUsuario");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("IdPerfil");

                    b.ToTable("TB_USUARIO", (string)null);
                });

            modelBuilder.Entity("DispositivoIot", b =>
                {
                    b.HasOne("Phycocarbon.Domain.Entities.Tanque", "Tanque")
                        .WithMany("Dispositivos")
                        .HasForeignKey("IdTanque")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tanque");
                });

            modelBuilder.Entity("Phycocarbon.Domain.Entities.AlertaCritico", b =>
                {
                    b.HasOne("Phycocarbon.Domain.Entities.MetricaTanque", "Metrica")
                        .WithMany("Alertas")
                        .HasForeignKey("IdMetrica")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Phycocarbon.Domain.Entities.Tanque", "Tanque")
                        .WithMany("Alertas")
                        .HasForeignKey("IdTanque")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Metrica");

                    b.Navigation("Tanque");
                });

            modelBuilder.Entity("Phycocarbon.Domain.Entities.DadoOrbital", b =>
                {
                    b.HasOne("Phycocarbon.Domain.Entities.Fazenda", "Fazenda")
                        .WithMany("DadosOrbitais")
                        .HasForeignKey("IdFazenda")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fazenda");
                });

            modelBuilder.Entity("Phycocarbon.Domain.Entities.Fazenda", b =>
                {
                    b.HasOne("Phycocarbon.Domain.Entities.Usuario", "UsuarioResponsavel")
                        .WithMany("Fazendas")
                        .HasForeignKey("IdUsuarioResponsavel")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_FAZENDA_USUARIO");

                    b.Navigation("UsuarioResponsavel");
                });

            modelBuilder.Entity("Phycocarbon.Domain.Entities.MetricaTanque", b =>
                {
                    b.HasOne("DispositivoIot", "Dispositivo")
                        .WithMany("Metricas")
                        .HasForeignKey("IdDispositivo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Phycocarbon.Domain.Entities.Tanque", "Tanque")
                        .WithMany("Metricas")
                        .HasForeignKey("IdTanque")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dispositivo");

                    b.Navigation("Tanque");
                });

            modelBuilder.Entity("Phycocarbon.Domain.Entities.PrevisaoIa", b =>
                {
                    b.HasOne("Phycocarbon.Domain.Entities.DadoOrbital", "DadoOrbital")
                        .WithMany("Previsoes")
                        .HasForeignKey("IdDadoOrbital")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Phycocarbon.Domain.Entities.Tanque", "Tanque")
                        .WithMany("Previsoes")
                        .HasForeignKey("IdTanque")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DadoOrbital");

                    b.Navigation("Tanque");
                });

            modelBuilder.Entity("Phycocarbon.Domain.Entities.Tanque", b =>
                {
                    b.HasOne("Phycocarbon.Domain.Entities.Fazenda", "Fazenda")
                        .WithMany("Tanques")
                        .HasForeignKey("IdFazenda")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TANQUE_FAZENDA");

                    b.Navigation("Fazenda");
                });

            modelBuilder.Entity("Phycocarbon.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("Phycocarbon.Domain.Entities.Perfil", "Perfil")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdPerfil")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_USUARIO_PERFIL");

                    b.Navigation("Perfil");
                });

            modelBuilder.Entity("DispositivoIot", b =>
                {
                    b.Navigation("Metricas");
                });

            modelBuilder.Entity("Phycocarbon.Domain.Entities.DadoOrbital", b =>
                {
                    b.Navigation("Previsoes");
                });

            modelBuilder.Entity("Phycocarbon.Domain.Entities.Fazenda", b =>
                {
                    b.Navigation("DadosOrbitais");

                    b.Navigation("Tanques");
                });

            modelBuilder.Entity("Phycocarbon.Domain.Entities.MetricaTanque", b =>
                {
                    b.Navigation("Alertas");
                });

            modelBuilder.Entity("Phycocarbon.Domain.Entities.Perfil", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Phycocarbon.Domain.Entities.Tanque", b =>
                {
                    b.Navigation("Alertas");

                    b.Navigation("Dispositivos");

                    b.Navigation("Metricas");

                    b.Navigation("Previsoes");
                });

            modelBuilder.Entity("Phycocarbon.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Fazendas");
                });
#pragma warning restore 612, 618
        }
    }
}
